### ISSUE TITLE
Any way to get this to work with Traktor?

### ISSUE THREAD

**Issue by FatCatLikesBeer** [maarten/Ximian#1]
swinsian2itlxml by Matt Hite worked just fine with Traktor. Any way to get this program to do the same? :)

**Comment by moebiusfrost** [comment]
@FatCatLikesBeer How did you solve the problem?

**Comment by FatCatLikesBeer** [comment]
@moebiusfrost sadly, I don't recollect. I think my solution was to stop using Traktor.
